openvpn_monitor:
  datetimeformat: "%%d/%%m/%%Y"
  latitude: -37
  longitude: 144
  maps: true
  mapsheight: 500
  site: test
  sites:
    - alias: UDP
      host: '185.252.215.176'
      name: UDP
      port: 5550
      showdisconnect: true
